### PR TITLE
merge urg_c with main branch, fix connecting with URG-04LX

### PR DESCRIPTION
**Pull request by bygreencn**
1.The reason of URG-04LX cound not work with urg_c:
 a. The response of VV-Command of URG-04LX has new-line "I\LF" and checksum of "Sensor Serial Number" is  WRONG, all of these make the version verify failed.
 b. more VV-Command send to URG-04LX will cause the device do not give response, which make serial connect failed.
2. Merge  main branch urg_c at sourceforge, which fix some issues.

NOT FIXED:
1. Wrong command may cause the device could not work except re-power-on, such as intensity and multi-echo request.

### CODE REVIEW

**Comment by boris-il-forte** [comment]
No news about this pull request? Now URG-04LX works only with the unsupported node.

**Comment by yif0** [comment]
have a similar problem

**Comment by dratasich** [comment]
same here
ROS kinetic urg_node not working with Hokuyo URG-04LX, but with depricated hokuyo_node

**Comment by ivanazcarate** [comment]
I am also having this problem.

**Comment by 2scholz** [comment]
For those having problems using the urg_node with the URG-04LX, I outlined a solution [here](https://github.com/ros-drivers/urg_node/issues/23).

**Pull request closed without merging**
